### ISSUE TITLE
libde265 doesn't compile as fat binary on Mac x86

### ISSUE THREAD

**Issue by nickorr** [GoyaPtyLtd/BaseElements-Plugin-Libraries#1]
I cannot seem to get a libde265 fat binary on my x86 machine.  lips -info is always x86 only.

I've tried both configure and cmake and a heap of variations of those.

Next option will be to try on arm and see if it can cross compile, or just do two builds and combine them with lipo.

**Comment by minstral** [comment]
G'day Nick,

I can compile here with:

    cmake .. -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DBUILD_SHARED_LIBS=OFF -DENABLE_DECODER=OFF

on both platforms. The boxes here don't have lips (!)... lipo gives:

    Architectures in the fat file: /Users/mark/Downloads/libde265-master/_build/libde265/libde265.a are: x86_64 arm64

Mark
