### ISSUE TITLE
beheif is missing a heap of includes...

### ISSUE THREAD

**Issue by nickorr** [GoyaPtyLtd/BaseElements-Plugin-Libraries#2]
libheif doesn't yet compile, it requires a heap of different references to work, and I'm not sure which is which.

Run the cmake to see what outputs it gives around references to libraries etc.

@minstral may be of assistance

**Comment by minstral** [comment]
Please try

     cmake --preset=release-noplugins .. -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DBUILD_SHARED_LIBS=OFF -DWITH_LIBDE265=YES -DLIBDE265_INCLUDE_DIR=$SRCROOT/Headers -DLIBDE265_LIBRARY=$SRCROOT/Libraries/macOS/libde265.a

Note: I needed to update the cmake on my box to get this to work.

**Comment by nickorr** [comment]
My Libheif is now working, and it's cross compiling too.  So the only option you're suggesting that I didn't have was :

--preset=release-noplugins

Do you know if that is important @minstral ?

**Comment by minstral** [comment]
From what I can see the version of the library we're using was compiled with --preset=release. Looking at the libheif docs now though, I'd try --preset=release-no-plugins unless it's causing a problem.

**Comment by nickorr** [comment]
I had that on Mac, but didn't on linux for some reason.  I've clarified it and added it to both now.  I'll close this one for now.
